### ISSUE TITLE
Issue with rostest and python coverage version 4.4

### ISSUE THREAD

**Issue by pbaughman** [ros/ros_comm#1055]
Our CI system just went from python coverage 4.3.4 to 4.4b1 and suddenly our ros tests are blowing up.  I'm not sure if this is an issue with coverage or an issue with rostest right now (still getting a minimum repro - leaning towards this being a coverage issue) but I wanted to put this out here in case someone else runs into the same problem.  The error we're seeing is in the following stack trace:

```
Traceback (most recent call last):
  File "/tmp/tmpRSLS3y/src/app/test/integration/test_bagfile_recorder.py", line 83, in <module>
    main()
  File "/tmp/tmpRSLS3y/src/app/test/integration/test_bagfile_recorder.py", line 79, in main
    rostest.rosrun(PKG, NAME, TestBagfileRecorder)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py", line 148, in rosrun
    _stop_coverage([package])
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py", line 227, in _stop_coverage
    _cov.stop()
  File "/usr/local/lib/python2.7/dist-packages/coverage/control.py", line 899, in analysis
    f, s, _, m, mf = self.analysis2(morf)
  File "/usr/local/lib/python2.7/dist-packages/coverage/control.py", line 920, in analysis2
    analysis = self._analyze(morf)
  File "/usr/local/lib/python2.7/dist-packages/coverage/control.py", line 935, in _analyze
    self.get_data()
  File "/usr/local/lib/python2.7/dist-packages/coverage/control.py", line 824, in get_data
    if self.collector.save_data(self.data):
  File "/usr/local/lib/python2.7/dist-packages/coverage/collector.py", line 382, in save_data
    covdata.add_lines(abs_file_dict(self.data))
  File "/usr/local/lib/python2.7/dist-packages/coverage/collector.py", line 377, in abs_file_dict
    return dict((abs_file(k), v) for k, v in iitems(d))
  File "/usr/local/lib/python2.7/dist-packages/coverage/collector.py", line 377, in <genexpr>
    return dict((abs_file(k), v) for k, v in iitems(d))
RuntimeError: dictionary changed size during iteration
```

This issue is present w/ coverage version 4.4b1 and 4.4 (see https://github.com/nedbat/coveragepy/blob/master/CHANGES.rst)  My hunch it's something to do with bullet point 3 under the release notes for 4.4b1:
> In previous versions, calling a method that used collected data would prevent further collection. For example, save(), report(), html_report(), and others would all stop collection. An explicit start() was needed to get it going again. This is no longer true. Now you can use the collected data and also continue measurement. Both issue 79 and issue 448 described this problem, and have been fixed.

This is more of a heads-up than anything.  I've also got an issue opened with python coverage here: https://bitbucket.org/ned/coveragepy/issues/581/44b1-44-breaking-in-ci

**Comment by pbaughman** [comment]
We were able to reproduce the issue in coverage without using any ROS stuff.  Closing
