### ISSUE TITLE
Configuration across IPV6 - Kinetic

### ISSUE THREAD

**Issue by richard-a-mck** [ros/ros_comm#1148]
Hi there. I'm having some issues with configuration of ROS across multiple machines using an ad-hoc network on a PC with Ubuntu 16, ROS Kinetic and a Raspberry Pi with Ubuntu 16 and ROS Kinetic. 
Someone on the ROS answers board suggested I raise an issue here. Here's the [link to my original post](https://answers.ros.org/question/269182/correct-ros_master_uri-format-for-ipv6/).
Of interest, on my PC if I set the master URI to 

**ROS_MASTER_URI=http://[fe80::ba27:ebff:feb8:fee8%wlxf4f26d11d066]:11311** 

and run _roswtf_ I get the following output:

```
Loaded plugin tf.tfwtf
No package or stack in context
Traceback (most recent call last):
  File "/opt/ros/kinetic/bin/roswtf", line 35, in <module>
    roswtf.roswtf_main()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roswtf/__init__.py", line 89, in roswtf_main
    _roswtf_main()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roswtf/__init__.py", line 172, in _roswtf_main
    wtf_check_environment(ctx)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roswtf/environment.py", line 219, in wtf_check_environment
    error_rule(r, r[0](ctx), ctx)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roswtf/rules.py", line 100, in error_rule
    _check_rule(rule, ret, ctx, ctx.errors, WtfError)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roswtf/rules.py", line 71, in _check_rule
    ctx_list.append(level(f_msg%d + ret%d, f_msg, ret))
ValueError: unsupported format character 'w' (0x77) at index 51
```

If I change my master_uri to the following, 

**ROS_MASTER_URI=http://[fe80::ba27:ebff:feb8:fee8%%wlxf4f26d11d066]:11311**
 
(note the double %), I get the following roswtf output:

```
Loaded plugin tf.tfwtf
No package or stack in context
================================================================================
Static checks summary:

Found 1 error(s).

ERROR ROS_MASTER_URI [http://[fe80::ba27:ebff:feb8:fee8%%wlxf4f26d11d066]:11311] is not a valid URL: invalid address string [[fe80::ba27:ebff:feb8:fee8%wlxf4f26d11d066]:11311]
================================================================================

ROS Master does not appear to be running.
Online graph checks will not be run.
ROS_MASTER_URI is [http://[fe80::ba27:ebff:feb8:fee8%%wlxf4f26d11d066]:11311]
```

I can successfully ping6 the address of the RPI (fe80... etc) and vice versa from the RPI. I can also ssh between the two devices without issue.

Is this a genuine issue or am I just misconfiguring something?

**Comment by richard-a-mck** [comment]
Also worth noting I have added _export ROS_IPV6=on_ to ~/.bashrc on both systems.

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.

**Comment by dirk-thomas** [comment]
Sorry just noticed the link to the existing question... Will reopen this again and try to answer...

**Comment by dirk-thomas** [comment]
In many locations the string containing the *uri* will be used and formatted using the `%` operator. Since classically it only contained IPv4 addresses it didn't contain `%` characters. In your case it does and when being used with the `%` operator it is being misinterpreted as `%w` which then fails.

This will likely need some substitutions of the single `%` with a double `%%` (similar to #585). It would be great if your could look into where that is necessary and propose a pull request to make it work for your use case.

**Comment by richard-a-mck** [comment]
After some quick investigation, it looks like the fix in #585 was only applied to Indigo. ~~My network.py file still has the original command. I'll try submit a PR to change this for Kinetic~~ My network.py has the following which should in theory fix this problem:
```python
# #1220
def ip_check(ctx):
    # best we can do is compare roslib's routine against socket resolution and make sure they agree
    local_addrs = rosgraph.network.get_local_addresses()

    resolved_ips = [host[4][0] for host in socket.getaddrinfo(socket.gethostname(), 0, 0, 0, socket.SOL_TCP)]
    global_ips = [ ip for ip in resolved_ips if not ip.startswith('127.') and not ip == '::1']

    remote_ips = list(set(global_ips) - set(local_addrs))
    if remote_ips:
        retval = "Local hostname [%s] resolves to [%s], which does not appear to be a local IP address %s." % (socket.gethostname(), ','.join(remote_ips), str(local_addrs))
        # IPv6 support % to denote zone/scope ids. The value is expanded
        # in other functions, this is why we are using replace command in
        # the return. For more info https://github.com/ros/ros_comm/pull/598
        return retval.replace('%', '%%')
```
I don't know enough about how roswtf or python works to comfortably fix this issue myself.

**Comment by dirk-thomas** [comment]
> After some quick investigation, it looks like the fix in #585 was only applied to Indigo.

The patch from #598 is available in all current branches - also in the latest `lunar-devel`.

> My network.py has the following which should in theory fix this problem:

The snipped you posted is exactly the same as the code currently on the `lunar-devel` branch: https://github.com/ros/ros_comm/blob/67633983de134d7e4c55c4d28956aa603eb42099/utilities/roswtf/src/roswtf/network.py#L47-L60

Therefore I am not sure what you are proposing and if the problem still exists for you.

**Comment by richard-a-mck** [comment]
The section I posted is supposed to be the code that fixes the IPv6 bug. It is also the code that is in-use on my system, where the IPv6 bug is present, suggesting that the fix doesn't work, at least in my case.
I've worked around it by reverting to IPv4 for this project. It would be good to test further with IPv6 addresses to figure out whether this was an issue unique to me or not. In saying that, I don't have sufficient understanding of python or the ROS network stack to resolve this myself.

**Comment by smithan7** [comment]
I am having the same issue with IPV6, any update on this? Has anyone had success with IPV6 and can point to a resource?

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as of today, May 31st 2025. I am archiving this repository because:

* it only supports ROS 1
* it isn't needed anymore in ROS 2

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
