### ISSUE TITLE
rosbag: check wrongly detect necessary migration

### ISSUE THREAD

**Issue by ablasdel** [ros/ros_comm#116]
I was trying to filter one of my bag and run into an assert:

```
Traceback (most recent call last):
  File "/opt/ros/fuerte/bin/rosbag", line 35, in <module>
    rosbag.rosbagmain()
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rosbag/rosbag_main.py", line 824, in rosbagmain
    cmds[cmd](argv[2:])
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rosbag/rosbag_main.py", line 293, in filter_cmd
    msg.deserialize(serialized_bytes)
  File "/tmp/genpy_GYSh3R/tmpci69Zq.py", line 115, in deserialize
genpy.message.DeserializationError: unpack requires a string argument of length 12
```

I therefore decided to check my bag with rosbag check. The latter produces erroneous statements, saying:

```
The following migrations need to occur:
 * From: tf/tfMessage [94810edda583a504dfda3829e70d7eec]
   To:   Unknown
    1 rules missing:
     * From: tf/tfMessage [94810edda583a504dfda3829e70d7eec]
       To:   Unknown
 * From: asebaros/AsebaEvent [49995036bad52e061c5fd515a11fffd7]
   To:   Unknown
    1 rules missing:
     * From: asebaros/AsebaEvent [49995036bad52e061c5fd515a11fffd7]
       To:   Unknown
 * From: marxbot_navigation_driver/Holes [f79b3052041f645c20f1cb9fee7adc96]
   To:   Unknown
    1 rules missing:
     * From: marxbot_navigation_driver/Holes [f79b3052041f645c20f1cb9fee7adc96]
       To:   Unknown
 * From: marxbot_navigation_driver/Prox [27b203bc6c0c45a3a402103ddc9ce94a]
   To:   Unknown
    1 rules missing:
     * From: marxbot_navigation_driver/Prox [27b203bc6c0c45a3a402103ddc9ce94a]
       To:   Unknown
 * From: lb_vision_driver/VisionData [f8bbeced64c960ab6a67ac05beb4925a]
   To:   Unknown
    1 rules missing:
     * From: lb_vision_driver/VisionData [f8bbeced64c960ab6a67ac05beb4925a]
       To:   Unknown
```

Note the statement about tf. This is wrong, as the tf message from /opt/ros/fuerte/stacks/geometry/tf has the right checksum, as shown by

```
rospack find tf
/opt/ros/fuerte/stacks/geometry/tf
```

and

```
grep 9481 /opt/ros/fuerte/stacks/geometry/tf/msg_gen/cpp/include/tf/tfMessage.h 
    return "94810edda583a504dfda3829e70d7eec";
```

Also note that both bags where created with fuerte on Ubuntu 12.04

Therefore, I guess there is a bug in rosbag.

**Comment by dirk-thomas** [comment]
I will close this ticket since further information is required to investigate it. Please feel free to comment and the ticket can be reopened.
