### ISSUE TITLE
AttributeError from publisher_update_task()

### ISSUE THREAD

**Issue by drigz** [ros/ros_comm#1389]
I've seen the following error from the rosmaster with ba141305:

```
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "[SNIP]/tools/rosmaster/src/rosmaster/threadpool.py", line 218, in run
  File "[SNIP]/tools/rosmaster/src/rosmaster/master_api.py", line 216, in publisher_update_task
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'time'
```

master_api.py:216 is:

```
        delta_sec = time.time() - start_sec
```

It's possible that the master_api module has been garbage collected, so its globals no longer exist ([as explained on SO](https://stackoverflow.com/questions/32282274/cannot-find-time-module-when-changed-sys-modules-name)). An example fix for this sort of issue can be seen here: https://github.com/benoitc/socketpool/pull/33/files

I can send a pull request if you think that's an appropriate fix.

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as of today, May 31st 2025. I am archiving this repository because:

* it only supports ROS 1
* it isn't needed anymore in ROS 2

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
