### ISSUE TITLE
Not handled `Errno 4` in tcpros_base ?

### ISSUE THREAD

**Issue by artivis** [ros/ros_comm#1554]
Creating a `ServiceProxy` in a `Thread` with the `persistent` parameter set to `True`, leads to the following issues.

First call seems to go fine, but second call results in the following,

On the service server side :

```sh
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 660, in handle
    requests = transport.receive_once()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 750, in receive_once
    raise TransportException("receive_once[%s]: unexpected error %s"%(self.name, str(e)))
TransportException: receive_once[/my_srv/start]: unexpected error [Errno 4] Interrupted system call
```

thrown [from here](https://github.com/ros/ros_comm/blob/kinetic-devel/clients/rospy/src/rospy/impl/tcpros_base.py#L750). 

On the client side:

```sh
process[joy_teleop-1]: started with pid [945]
process[joystick-2]: started with pid [950]
Exception in thread Thread-61:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
```

One the client side for third and subsequent calls:

```sh
Exception in thread Thread-62:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 512, in call
    transport.send_message(request, self.seq)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 666, in send_message
    self.write_data(self.write_buff.getvalue())
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 690, in write_data
    raise TransportTerminated(str(errno)+msg)
TransportTerminated: 32Broken pipe
```

system: 
Ubuntu 16.04
ROS Kinetic
Python 2.7.12

Related issue : https://github.com/ros-teleop/teleop_tools/issues/28

**Comment by Arusekk** [comment]
https://github.com/ros/ros_comm/blob/767174722ef95249aeaced2103acb703c302d13c/clients/rospy/src/rospy/impl/tcpros_base.py#L735

this line should be wrapped in something like:

```py
try:
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
except socket.error as e:
    if e.errno == errno.EINTR:
        continue
    else:
        raise
```

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as of today, May 31st 2025. I am archiving this repository because:

* it only supports ROS 1
* it isn't needed anymore in ROS 2

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
