### ISSUE TITLE
python script can't write compressed image to bag

### ISSUE THREAD

**Issue by mpitropov** [ros/ros_comm#1564]
I have a simple script that allows you to shift the images in a bag forward or backwards in time. I used this often up until April 2018. Now when I try to run it I get an error that occurs when I write the compressed image to the topic. There is also a strange issue where rosbag check shows that the compressed image topic needs to be migrated but the hash is the same. Has there been any recent API changes to cause this problem?

Edit: I did perform an upgrade from ```ros-kinetic-sensor-msgs:amd64 (1.12.6-0xenial-20180824-104202-0800, 1.12.7-0xenial-20181107-004110-0800)```

Error:
```
Reading bag 2017-08-06-22-03-37_0.bag
Copying ros messages and shifting images into outbag
Traceback (most recent call last):
  File "image_shifter.py", line 74, in <module>
    main()
  File "image_shifter.py", line 66, in main
    print(' [DONE]')
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbag/bag.py", line 184, in __exit__
    self.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbag/bag.py", line 415, in close
    self._stop_writing()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbag/bag.py", line 1261, in _stop_writing
    self.flush()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbag/bag.py", line 285, in flush
    self._stop_writing_chunk()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbag/bag.py", line 1321, in _stop_writing_chunk
    self._write_chunk_header(chunk_header)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbag/bag.py", line 1382, in _write_chunk_header
    'size':        _pack_uint32(chunk_header.uncompressed_size)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbag/bag.py", line 1596, in _pack_uint32
    def _pack_uint32(v): return struct.pack('<L', v)
struct.error: integer out of range for 'L' format code
```

Rosbag check:
```
The following migrations need to occur:
 * From: sensor_msgs/CompressedImage [8f7a12909da2c9d3332d540a0977563f]
   To:   sensor_msgs/CompressedImage [8f7a12909da2c9d3332d540a0977563f]
 * From: anm_msgs/VehicleState [83cb7fb9eb0225599d87dab7d1d7aed8]
   To:   anm_msgs/VehicleState [83cb7fb9eb0225599d87dab7d1d7aed8]
 * From: dataspeed_can_msgs/CanMessageStamped [33747cb98e223cafb806d7e94cb4071f]
   To:   can_msgs/Frame [64ae5cebf967dc6aae4e78f5683a5b25]
 * From: dbw_mkz_msgs/ThrottleReport [a7fd7b93c8549e83c319e38a18f6dbdc]
   To:   dbw_mkz_msgs/ThrottleReport [8a31a867d359c6c8fca5fc5cc387567e]
 * From: dbw_mkz_msgs/SteeringReport [25bf2c220d904531d8bc16ab5271325d]
   To:   dbw_mkz_msgs/SteeringReport [6f32c1fc98edaf75e24a770b2ae3abfc]
 * From: dbw_mkz_msgs/BrakeReport [a306c167d365176ae6159e3c4e3f3197]
   To:   dbw_mkz_msgs/BrakeReport [a92bad28c400885f36170c1cab44618e]
 * From: dbw_mkz_msgs/GearReport [f33342dfeb80c29d8fe4b31e22519594]
   To:   dbw_mkz_msgs/GearReport [785b94d5bfee677e7f0da982153f2711]
 * From: dbw_mkz_msgs/Misc1Report [9ecd16fb81815b3e46e0550feea1da2f]
   To:   dbw_mkz_msgs/Misc1Report [036c26779fee8ddc637f32d336e03b66]

No additional rule files needed to be generated.  diagnostics.bmr not created.
```

Here is the whole script if you are interested:
```
#!/usr/bin/env python

# This script will shift the images in a bag by the seconds that are in
# the specified amount of hours.
#
# Usage
# python image_shifter.py /path/of/bags/ <number_of_hours>

import sys, os, rosbag
from sets import Set

bag_path=''
time_shift=0

if len(sys.argv) == 3:
    bag_path = sys.argv[1]
    time_shift = int(sys.argv[2])
    os.chdir(bag_path)
else:
    print('Please enter the path of the bags and the hours to shift.')
    exit()

bag_names = []
# Add all bags in bag_path to bag_names
for file in sorted(os.listdir(bag_path)):
    if file.endswith(".bag"):
        bag_names.append(file)

cam_topics = Set([
    '/ximea_camera_cam_b/compressed',
    '/ximea_camera_cam_f/compressed',
    '/ximea_camera_cam_fl/compressed',
    '/ximea_camera_cam_fr/compressed',
    '/ximea_camera_cam_lb/compressed',
    '/ximea_camera_cam_lf/compressed',
    '/ximea_camera_cam_rb/compressed',
    '/ximea_camera_cam_rf/compressed'
])

cam_topics_found = []

def main():
    for i in range(len(bag_names)):
        print('Reading bag ' + bag_names[i])

        with rosbag.Bag(bag_path + 'shift_' + bag_names[i], 'w') as outbag:
            count = 0.0  # Init as float
            msg_total = rosbag.Bag(bag_names[i]).get_message_count()

            print('Copying ros messages and shifting images into outbag')
            for topic, msg, t in rosbag.Bag(bag_names[i]).read_messages():
                # Write to the outbag if the topic is valid
                if topic in cam_topics:
                    t.secs += 60 * 60 * time_shift
                    outbag.write(topic, msg, t)
                else:
                    outbag.write(topic, msg, t)

                # Increase count of finished messages
                count += 1

                # Display progress
                progress = (count/msg_total) * 100
                display_progress(progress)
            # Finished
            print(' [DONE]')

# Display progress function
# Prints out the current progress on the same line
def display_progress(progress):
    sys.stdout.write("\r" + 'PROGRESS ' + format(progress, '.2f') + '%')
    sys.stdout.flush()

main()
```

**Comment by mpitropov** [comment]
@dirk-thomas @tfoote This occurs on images and compressed images where the md5sum is the same but it says they need to be migrated. I'm not sure if this is a change in python that broke something for me or if the ros bag migration code has something to do with this. Why do those messages need to be migrated?

I only see this change:
https://github.com/ros/common_msgs/commit/ebe34799eb85f43a2e8f6fca3a7e136f648d5f06

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as of today, May 31st 2025. I am archiving this repository because:

* it only supports ROS 1
* it isn't needed anymore in ROS 2

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
