### ISSUE TITLE
psutil.ZombieProcess process related with rosbag

### ISSUE THREAD

**Issue by cecilMao** [ros/ros_comm#1569]
Hi, when I tried to use rosbag, I met the following error.
```
Traceback (most recent call last):
 File "/opt/ros/melodic/bin/rosbag", line 34, in <module>
    import rosbag
  File "/opt/ros/melodic/lib/python2.7/site-packages/rosbag/__init__.py", line 33, in <module>
    from .bag import Bag, Compression, ROSBagException, ROSBagFormatException, ROSBagUnindexedException
  File "/opt/ros/melodic/lib/python2.7/site-packages/rosbag/bag.py", line 55, in <module>
    import gnupg
  File "/usr/local/lib/python2.7/site-packages/gnupg/__init__.py", line 23, in <module>
    from . import gnupg
  File "/usr/local/lib/python2.7/site-packages/gnupg/gnupg.py", line 42, in <module>
    from ._meta    import GPGBase
  File "/usr/local/lib/python2.7/site-packages/gnupg/_meta.py", line 134, in <module>
    class GPGBase(object):
  File "/usr/local/lib/python2.7/site-packages/gnupg/_meta.py", line 72, in __new__
    if cls._find_agent():
  File "/usr/local/lib/python2.7/site-packages/gnupg/_meta.py", line 115, in _find_agent
    if (proc.name() == "gpg-agent") and proc.is_running():
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 610, in name
    cmdline = self.cmdline()
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 663, in cmdline
    return self._proc.cmdline()
  File "/usr/local/lib/python2.7/site-packages/psutil/_psosx.py", line 342, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/psutil/_psosx.py", line 426, in cmdline
    return cext.proc_cmdline(self.pid)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/psutil/_psosx.py", line 373, in catch_zombie
    raise ZombieProcess(proc.pid, proc._name, proc._ppid)
psutil._exceptions.ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=62522)
```

Found a similar issue: [python-gnupg#201](https://github.com/isislovecruft/python-gnupg/issues/201).

Looks like need to kill ZombieProcess manually before running rosbag.

**Comment by dirk-thomas** [comment]
Please provide a reproducible steps for your problem.

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as of today, May 31st 2025. I am archiving this repository because:

* it only supports ROS 1
* it isn't needed anymore in ROS 2

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
