### ISSUE TITLE
roscpp: Date/Time parameters handled incorrectly  (ros ticket #3588)

### ISSUE THREAD

**Issue by tfoote** [ros/ros_comm#159]
I do:
rosparam set date1 2011-09-07T18:22:42

and retrieve a XmlRpcValue from the parameter server.
The struct tm that is returned has tm_year == 2011 and tm_mon == 9.

According to the manpage:

tm_mon    The number of months since January, in the range 0 to 11.
tm_year   The number of years since 1900.

I would expect tm_mon to be 8 and tm_year to be 111.

I am not sure if this is caused by the parameter server or rosparam.

Additionally rosparam asserts on get:

rosparam get /date1
Traceback (most recent call last):
  File "/opt/ros/diamondback/ros/bin/rosparam", line 40, in <module>
    rosparam.yamlmain()
  File "/opt/ros/diamondback/stacks/ros_comm/tools/rosparam/src/rosparam.py", line 633, in yamlmain
    _rosparam_cmd_get_dump(command, argv)
  File "/opt/ros/diamondback/stacks/ros_comm/tools/rosparam/src/rosparam.py", line 454, in _rosparam_cmd_get_dump
    _rosparam_cmd_get_param(script_resolve_name(NAME, arg), pretty=options.pretty, verbose=options.verbose)
  File "/opt/ros/diamondback/stacks/ros_comm/tools/rosparam/src/rosparam.py", line 283, in _rosparam_cmd_get_param
    dump = yaml.dump(val)
  File "/usr/lib/python2.6/dist-packages/yaml/__init__.py", line 175, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/lib/python2.6/dist-packages/yaml/**init**.py", line 165, in dump_all
    dumper.represent(data)
  File "/usr/lib/python2.6/dist-packages/yaml/representer.py", line 33, in represent
    node = self.represent_data(data)
  File "/usr/lib/python2.6/dist-packages/yaml/representer.py", line 46, in represent_data
    if self.ignore_aliases(data):
  File "/usr/lib/python2.6/dist-packages/yaml/representer.py", line 147, in ignore_aliases
    if data in [None, ()]:
  File "/usr/lib/python2.6/xmlrpclib.py", line 419, in **eq**
    s, o = self.make_comparable(other)
  File "/usr/lib/python2.6/xmlrpclib.py", line 399, in make_comparable
    (self.**class**.**name**, otype))
TypeError: Can't compare DateTime and NoneType

Running diamondback from packages on Lucid.

trac data:
- Owner: **dthomas**
- Reporter: **dornhege**
- Reported at: **Thu Jul 14 07:51:46 2011**
- URL: https://code.ros.org/trac/ros/ticket/3588

**Comment by tfoote** [comment]
[kwc] moved from https://code.ros.org/trac/ros-pkg/ticket/5064

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as of today, May 31st 2025. I am archiving this repository because:

* it only supports ROS 1
* it isn't needed anymore in ROS 2

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
