### ISSUE TITLE
rostest: throws python exceptions with camera1394 under Groovy

### ISSUE THREAD

**Issue by jack-oquin** [ros/ros_comm#173]
I am pretty confident this is not a driver problem. It can stream data from this camera at the expected Hz rate, even under Groovy.

The exact same (dry) source tree works fine on Fuerte.

To reproduce: 
- check out git@github.com:ros-drivers/camera1394.git
- rosmake camera1394
- rostest camera1394  camera_nodelet_hz.test

Results:

``` javascript
$ rostest camera1394 camera_nodelet_hz.test 
... logging to /home/joq/.ros/log/rostest-vision-4-21691.log
[ROSUNIT] Outputting test results to /home/joq/.ros/test_results/camera1394/rostest-tests_camera_nodelet_hz.xml
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 562, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 544, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 271, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 246, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 236, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 577, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 476, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 339, in _init_posix
    _parse_makefile(makefile, vars)
  File "/usr/lib/python2.7/sysconfig.py", line 220, in _parse_makefile
    _findvar1_rx = re.compile(r"\$\(([A-Za-z][A-Za-z0-9_]*)\)")
  File "/usr/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 240, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python2.7/sre_compile.py", line 500, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python2.7/sre_parse.py", line 673, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python2.7/sre_parse.py", line 308, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python2.7/sre_parse.py", line 633, in _parse
    p = _parse_sub(source, state)
  File "/usr/lib/python2.7/sre_parse.py", line 308, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python2.7/sre_parse.py", line 508, in _parse
    if subpattern:
  File "/usr/lib/python2.7/sre_parse.py", line 126, in __len__
    def __len__(self):
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 562, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 544, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 271, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 246, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 236, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 577, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 476, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 350, in _init_posix
    parse_config_h(f, vars)
  File "/usr/lib/python2.7/sysconfig.py", line 397, in parse_config_h
    if m:
KeyboardInterrupt

```

**Comment by jack-oquin** [comment]
Note: no keyboard interrupt was actually typed in this test.

**Comment by jack-oquin** [comment]
I just noticed that this and another failing test is declared with the less-common rostest labelled macro:

```
robuild_add_rostest_labeled(device tests/camera_nodelet_hz.test)
```

Also, do not check out the `master` branch to verify this problem, use `groovy-devel`.

**Comment by dirk-thomas** [comment]
This seems to be not reproducible with having an device connected when running the unit tests. Is this actually still a problem?

**Comment by jack-oquin** [comment]
I dug up an old system with groovy installed, and ran the same test.

It's working now. Closing the issue.
