### ISSUE TITLE
Can not restart a node from the same python process

### ISSUE THREAD

**Issue by PierrickKoch** [ros/ros_comm#185]
Is there a way to restart a node from the same python process ?

``` python
import rospy
rospy.init_node("plop")
rospy.is_shutdown() # False
rospy.signal_shutdown("fin")
rospy.is_shutdown() # True
rospy.init_node("plop")
rospy.is_shutdown() # True (still !)

# try with a new node name

rospy.init_node("plop2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rospy/client.py", line 273, in init_node
    raise rospy.exceptions.ROSException("rospy.init_node() has already been called with different arguments: "+str(_init_node_args))
rospy.exceptions.ROSException: rospy.init_node() has already been called with different arguments: ('plop', [''], False, None, False, False)

del rospy
import rospy
import imp
imp.reload(rospy)
rospy.init_node("plop")
rospy.is_shutdown() # True (still !!!)
```

It seems that there are many globals in:
https://github.com/ros/ros_comm/blob/groovy-devel/clients/rospy/src/rospy/core.py

**Comment by dirk-thomas** [comment]
Reinitializing a ROS node or starting another node after shutting the first one down is currently not supported - neither in C++ nor in Python.
