### ISSUE TITLE
rostopic hz is broken when using with several topics

### ISSUE THREAD

**Issue by augustinmanecy** [ros/ros_comm#2091]
in ROS melodic it was possible to use rostopic monitor with several topics name in order to monitor simultaneously several topics frequency.

It seems this feature is broken because python3 replace xrange by range, and some xrange calls are still here. 

Here is an example of the bug, I called rotopic hz for each topic first, and then, for both topics simultenaously:

```bash
robotis@m600:~/ros1_ws$ rostopic hz /m600/xsens/imu_data
subscribed to [/m600/xsens/imu_data]
average rate: 100.122
	min: 0.008s max: 0.012s std dev: 0.00047s window: 99
average rate: 100.065
	min: 0.008s max: 0.012s std dev: 0.00042s window: 200
^Caverage rate: 100.056
	min: 0.008s max: 0.012s std dev: 0.00039s window: 236
robotis@m600:~/ros1_ws$ rostopic hz /m600/xsens/delta_q
subscribed to [/m600/xsens/delta_q]
average rate: 100.280
	min: 0.007s max: 0.011s std dev: 0.00033s window: 99
average rate: 100.139
	min: 0.007s max: 0.012s std dev: 0.00038s window: 199
^Caverage rate: 100.111
	min: 0.007s max: 0.012s std dev: 0.00035s window: 243
robotis@m600:~/ros1_ws$ rostopic hz /m600/xsens/delta_q /m600/xsens/imu_data
subscribed to [/m600/xsens/delta_q]
subscribed to [/m600/xsens/imu_data]
Traceback (most recent call last):
  File "/opt/ros/noetic/bin/rostopic", line 35, in <module>
    rostopic.rostopicmain()
  File "/opt/ros/noetic/lib/python3/dist-packages/rostopic/__init__.py", line 2132, in rostopicmain
    _rostopic_cmd_hz(argv)
  File "/opt/ros/noetic/lib/python3/dist-packages/rostopic/__init__.py", line 1523, in _rostopic_cmd_hz
    _rostopic_hz(topics, window_size=window_size, filter_expr=filter_expr,
  File "/opt/ros/noetic/lib/python3/dist-packages/rostopic/__init__.py", line 323, in _rostopic_hz
    rt.print_hz(topics)
  File "/opt/ros/noetic/lib/python3/dist-packages/rostopic/__init__.py", line 270, in print_hz
    print(_get_ascii_table(header, stats))
  File "/opt/ros/noetic/lib/python3/dist-packages/rostopic/__init__.py", line 285, in _get_ascii_table
    body = '\n'.join('   '.join(cols[h][i] for h in header) for i in xrange(n_rows))
NameError: name 'xrange' is not defined
```

**Comment by augustinmanecy** [comment]
I missed that: use range instead of xrange #2013
