### ISSUE TITLE
Melodic: roswtf tests missing dependency

### ISSUE THREAD

**Issue by kyrofa** [ros/ros_comm#2138]
On Ubuntu 18.04 I have a Melodic workspace containing only ros_comm (on the melodic-devel branch), and only rosdep installed. Assume I've also worked around #2136 by adding more packages to the online/offline tests. I do the following:

1. `rosdep install -y -i --from-paths path/to/ros_comm_ws`
2. `source /opt/ros/melodic/setup.sh`
3. `catkin_make_isolated`
4. `source devel_isolated/setup.sh`
5. `catkin_make_isolated --force-cmake --catkin-make-args run_tests`

roswtf tests fail:

```
<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="3" errors="0" failures="1" skip="0"><testcase classname="test.test_roswtf_command_line_offline.TestRoswtfOffline" name="test_cmd_help" time="0.203"></testcase><testcase classname="test.test_roswtf_command_line_offline.TestRoswtfOffline" name="test_offline" time="24.090"><failure type="exceptions.AssertionError" message="OUTPUT[================================================================================&#10;Static checks summary:&#10;&#10;Found 1 warning(s).&#10;Warnings are things that may be just fine, but are sometimes at fault&#10;&#10;?[1mWARNING?[0m pycrypto is not installed&#10;&#10;================================================================================&#10;&#10;ROS Master does not appear to be running.&#10;Online graph checks will not be run.&#10;ROS_MASTER_URI is [http://localhost:11312]&#10;]"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/ubuntu/ws/src/ros_comm/utilities/roswtf/test/test_roswtf_command_line_offline.py", line 114, in test_offline
    self._check_output(output)
  File "/home/ubuntu/ws/src/ros_comm/utilities/roswtf/test/test_roswtf_command_line_offline.py", line 120, in _check_output
    'OUTPUT[%s]' % output)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: OUTPUT[================================================================================
Static checks summary:

Found 1 warning(s).
Warnings are things that may be just fine, but are sometimes at fault

?[1mWARNING?[0m pycrypto is not installed

================================================================================

ROS Master does not appear to be running.
Online graph checks will not be run.
ROS_MASTER_URI is [http://localhost:11312]
]
]]></failure></testcase><testcase classname="test.test_roswtf_command_line_offline" name="get_test_path" time="0.000"></testcase></testsuite>
```

Nothing in ros_comm seemingly depends upon `python-crypto`, so yes, it's not installed. SHOULD something depend on it, perhaps a test_depend for roswtf? Or should this test be updated to ignore that warning?

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as of today, May 31st 2025. I am archiving this repository because:

* it only supports ROS 1
* it isn't needed anymore in ROS 2

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
