### ISSUE TITLE
rosbag fix --force crashes if it does not find a migration path

### ISSUE THREAD

**Issue by bst** [ros/ros_comm#2140]
Assume having an old bag file `oldbag.bag` that contains several outdated messages `TestMessageA` and `TestMessageB`. You only have a migration rule `TestMessageA.bmr` but none for `TestMessageB`.

According to the help string [here](https://github.com/ros/ros_comm/blob/b6c23e1282815823c8e07b47384391cf7cf0eab4/tools/rosbag/src/rosbag/rosbag_main.py#L406), `--force` should `proceed with migrations, even if not all rules defined`.

But instead, it currently crashes due to an uncaught `BagMigrationException`:

```
$ rosbag fix --force data/oldbag.bag migrated.bag rules/TestMessageA.bmr 

Traceback (most recent call last):
  File "/home/bst/ws_roscomm/devel/bin/rosbag", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/bst/ws_roscomm/src/ros_comm/tools/rosbag/scripts/rosbag", line 35, in <module>
    rosbag.rosbagmain()
  File "/home/bst/ws_roscomm/src/ros_comm/tools/rosbag/src/rosbag/rosbag_main.py", line 1026, in rosbagmain
    cmds[cmd](argv[2:])
  File "/home/bst/ws_roscomm/src/ros_comm/tools/rosbag/src/rosbag/rosbag_main.py", line 457, in fix_cmd
    migrations = fixbag2(migrator, inbag_filename, outname, options.force)
  File "/home/bst/ws_roscomm/src/ros_comm/tools/rosbag/src/rosbag/migration.py", line 172, in fixbag2
    mig_msg = migrator.migrate_raw(msg, (new_msg_type._type, None, new_msg_type._md5sum, None, new_msg_type))
  File "/home/bst/ws_roscomm/src/ros_comm/tools/rosbag/src/rosbag/migration.py", line 1072, in migrate_raw
    raise BagMigrationException("Migrate called, but no valid migration path from [%s] to [%s]"%(msg_from[0], msg_to[0]))
rosbag.migration.BagMigrationException: Migrate called, but no valid migration path from [migration_test/TestMessageB] to [migration_test/TestMessageB]
```

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as of today, May 31st 2025. I am archiving this repository because:

* it only supports ROS 1
* it isn't needed anymore in ROS 2

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
