### ISSUE TITLE
[roscpp] Fix a issue where CallbackQueue::removeByID will unlock a lock that it does not hold

### ISSUE THREAD

**Issue by mitchellwills** [ros/ros_comm#219]
If an exception is thrown in a callback then the callback queue will not reach

```
tls->calling_in_this_thread = last_calling;
```

as a result if removeByID is called to remove that callback it will unlock the mutex (but the mutex was already unlocked when the exception was thrown because the rw_lock went out of scope. However calling_in_this_thread is still set and the following will execute

```
if (tls_->calling_in_this_thread == id_info->id)
{
  id_info->calling_rw_mutex.unlock_shared();
}
```

this will put calling_rw_mutex into and invalid state such that the program will hang on the next line

```
boost::unique_lock<boost::shared_mutex> rw_lock(id_info->calling_rw_mutex);
```

when it tries to aquire the mutex.
Somehow the calling_in_this_thread value should be restored even in the case of an exception being thrown.

**Comment by dirk-thomas** [comment]
Can you please provide a simple and easy to run example which reproduces the issue?

**Comment by mitchellwills** [comment]
You can get my example package here (http://users.wpi.edu/~mwills/ros_error_test.zip)
It contains one node which is described below. The raw source for the node is at the bottom of this comment
This will run with the following output and the freeze

```
[ INFO] [1366743190.413979916]: SPINNING
[ INFO] [1366743190.513851390]: Count: 1
[ INFO] [1366743190.613486888]: Count: 2
[ INFO] [1366743190.713112766]: Count: 3
[ INFO] [1366743190.813654080]: Count: 4
[ INFO] [1366743190.913405780]: Count: 5
[ INFO] [1366743191.013114843]: Count: 6
[ INFO] [1366743191.112734673]: Count: 7
[ INFO] [1366743191.213456045]: Count: 8
[ INFO] [1366743191.313073070]: Count: 9
[ INFO] [1366743191.413721263]: Count: 10
[ INFO] [1366743191.414222118]: GOT EXCEPTION
[ INFO] [1366743191.414370609]: STOPPING TIMER
```

And GDB gives the following backtrace

```
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:162
#1  0x00007ffff7b3b357 in boost::unique_lock<boost::shared_mutex>::lock() () from /opt/ros/groovy/lib/libroscpp.so
#2  0x00007ffff7b39bdc in ros::CallbackQueue::removeByID(unsigned long) () from /opt/ros/groovy/lib/libroscpp.so
#3  0x00007ffff7b199b5 in ros::TimerManager<ros::Time, ros::Duration, ros::TimerEvent>::remove(int) () from /opt/ros/groovy/lib/libroscpp.so
#4  0x00007ffff7b18685 in ros::Timer::Impl::stop() () from /opt/ros/groovy/lib/libroscpp.so
#5  0x0000000000401bf8 in main (argc=1, argv=0x7fffffffdf88) at /home/mitchell/srr/aero_srr/error_test/src/node.cpp:29
```

Here is the raw source for the node

```
#include "ros/ros.h"
#include <exception>
int count = 0;
void callback(const ros::TimerEvent& event)
{
  ROS_INFO_STREAM("Count: "<<(++count));
  if(count==10)
    throw std::exception();
}

int main(int argc, char **argv)
{
  ros::init(argc, argv, "error_maker");

  ros::NodeHandle n;

  ros::Timer timer = n.createTimer(ros::Duration(0.1), &callback);

  ROS_INFO("SPINNING");

  try{
    ros::spin();
  } catch(std::exception& e){
    ROS_INFO("GOT EXCEPTION");
  }

  ROS_INFO("STOPPING TIMER");

  timer.stop();

  ROS_INFO("QUITTING");

  return 0;
}
```
