### ISSUE TITLE
rospy Melodic: Use of nonexisting symbol! (Bad backport from Noetic)

### ISSUE THREAD

**Issue by peci1** [ros/ros_comm#2271]
This got into the melodic-devel branch https://github.com/ros/ros_comm/blame/melodic-devel/clients/rospy/src/rospy/impl/tcpros_base.py#L157

_Originally posted by @v-lopez in https://github.com/ros/ros_comm/issues/1908#issuecomment-965042784_

I second @v-lopez's good eye and support it with a real-life stack trace:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 164, in run
    except ConnectionAbortedError:
NameError: global name 'ConnectionAbortedError' is not defined
```

This needs to be fixed ASAP. I don't know how did the change get into Melodic, but it is (should?) basically be thrown every time there is a socket error other than timeout. It's weird, because it should be around since rospy 1.14.5 (March 2020), so I guess it should have hit a lot more people...

I think the proper fix for Python 2 would be to just remove the except clause. Do the maintainers agree?

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as of today, May 31st 2025. I am archiving this repository because:

* it only supports ROS 1
* it isn't needed anymore in ROS 2

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
