### ISSUE TITLE
rostopic echo --bag  --filter /topicname does not limit messages filtered to /topicname

### ISSUE THREAD

**Issue by phil-marble** [ros/ros_comm#2304]
rostopic echo --bag  --filter /topicname does not limit messages filtered to /topicname

rosbag play &  rostopic echo -filter /topicname seems to work as expected

Bug reproduced in:
`ii  ros-noetic-rostopic                         1.15.14-1focal.20220926.212026                amd64`

```
$ rostopic echo --bag=$HOME/bagfiles/XXX.bag /topicname --filter="status=='something'"
Traceback (most recent call last):
  File "/opt/ros/noetic/bin/rostopic", line 35, in <module>
    rostopic.rostopicmain()
  File "/opt/ros/noetic/lib/python3/dist-packages/rostopic/__init__.py", line 2130, in rostopicmain
    _rostopic_cmd_echo(argv)
  File "/opt/ros/noetic/lib/python3/dist-packages/rostopic/__init__.py", line 1406, in _rostopic_cmd_echo
    _rostopic_echo(topic, callback_echo, bag_file=options.bag)
  File "/opt/ros/noetic/lib/python3/dist-packages/rostopic/__init__.py", line 1015, in _rostopic_echo
    _rostopic_echo_bag(callback_echo, bag_file)
  File "/opt/ros/noetic/lib/python3/dist-packages/rostopic/__init__.py", line 998, in _rostopic_echo_bag
    callback_echo.callback(msg, {'topic': t}, current_time=timestamp)
  File "/opt/ros/noetic/lib/python3/dist-packages/rostopic/__init__.py", line 898, in callback
    if self.filter_fn is not None and not self.filter_fn(data):
  File "/opt/ros/noetic/lib/python3/dist-packages/rostopic/__init__.py", line 1314, in eval_fn
    return eval(expr)
  File "<string>", line 1, in <module>
NameError: name 'status' is not defined

```

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as of today, May 31st 2025. I am archiving this repository because:

* it only supports ROS 1
* it isn't needed anymore in ROS 2

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
