### ISSUE TITLE
ugly rosparam get stack trace

### ISSUE THREAD

**Issue by tkruse** [ros/ros_comm#265]
e.g.:

```
rosparam get foo
Traceback (most recent call last):
  File "/opt/ros/fuerte/bin/rosparam", line 35, in <module>
    rosparam.yamlmain()
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rosparam/__init__.py", line 604, in yamlmain
    _rosparam_cmd_get_dump(command, argv)
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rosparam/__init__.py", line 428, in _rosparam_cmd_get_dump
    _rosparam_cmd_get_param(script_resolve_name(NAME, arg), pretty=options.pretty, verbose=options.verbose)
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rosparam/__init__.py", line 255, in _rosparam_cmd_get_param
    val = get_param(param)
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rosparam/__init__.py", line 208, in get_param
    return get_param_server().getParam(param)
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rosgraph/masterapi.py", line 206, in getParam
    return self._succeed(self.handle.getParam(self.caller_id, key))
  File "/opt/ros/fuerte/lib/python2.7/dist-packages/rosgraph/masterapi.py", line 154, in _succeed
    raise Error(msg)
rosgraph.masterapi.MasterError: Parameter [/foo] is not set
```

Same for hydro and groovy.

**Comment by dirk-thomas** [comment]
Same for `rosparam delete`.
