### ISSUE TITLE
rostopic echo array member with index no longer works.

### ISSUE THREAD

**Issue by ahendrix** [ros/ros_comm#282]
Worked in Fuerte and earlier versions of ros_comm in Groovy; no longer works:

Groovy:

```
$ rostopic echo -n1 /r_forearm_cam/camera_info/P
[464.95364, 0.0, 319.96278, 0.0, 0.0, 531.58521, 243.79679, 0.0, 0.0, 0.0, 1.0, 0.0]

---
$ rostopic echo -n1 /r_forearm_cam/camera_info/P[0]
Traceback (most recent call last):
  File "/opt/ros/groovy/bin/rostopic", line 35, in <module>
    rostopic.rostopicmain()
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rostopic/__init__.py", line 1666, in rostopicmain
    _rostopic_cmd_echo(argv)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rostopic/__init__.py", line 1026, in _rostopic_cmd_echo
    _rostopic_echo(topic, callback_echo, bag_file=options.bag)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rostopic/__init__.py", line 692, in _rostopic_echo
    index = submsg_class.__slots__.index(field)
ValueError: 'P[0]' is not in list
```

Fuerte:

```
$ rostopic echo -n1 /r_forearm_cam/camera_info/P
[464.95364, 0.0, 319.96278, 0.0, 0.0, 531.58521, 243.79679, 0.0, 0.0, 0.0, 1.0, 0.0]

---
$ rostopic echo -n1 /r_forearm_cam/camera_info/P[0]
464.95364

---
```

**Comment by dirk-thomas** [comment]
It seems to work fine for me with current Groovy packages:

```
$ rostopic echo /foo
header: 
  seq: 21
  stamp: 
    secs: 0
    nsecs: 0
  frame_id: ''
height: 0
width: 0
distortion_model: ''
D: []
K: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
R: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
P: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---

$ rostopic echo /foo/P
[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---

$ rostopic echo /foo/P[3]
0.4
---
$ rostopic echo /foo
header: 
  seq: 21
  stamp: 
    secs: 0
    nsecs: 0
  frame_id: ''
height: 0
width: 0
distortion_model: ''
D: []
K: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
R: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
P: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---

$ rostopic echo /foo/P
[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---

$ rostopic echo /foo/P[3]
0.4
---
```

Can you please check which package versions you are using and comment with your numbers of e.g. ros-groovy-rostopic?

**Comment by dirk-thomas** [comment]
I am closing this ticket for now since it clearly worked for me and no further information was provided. If it is still an issue (or even if it has been solved) please comment and the ticket can be reopened.
