### ISSUE TITLE
Importing tf in python fails because of undefined symbol

### ISSUE THREAD

**Issue by sksellio** [ros/ros_comm#31]
Importing tf fails with this error:

```
Traceback (most recent call last):
  File "test/arm_mover_test.py", line 6, in <module>
    from moveit_commander.commander import MoveGroupCommander
  File "/u/selliott/moveit/src/moveit_commander/src/moveit_commander/__init__.py", line 1, in <module>
    from commander import *
  File "/u/selliott/moveit/src/moveit_commander/src/moveit_commander/commander.py", line 38, in <module>
    import tf
  File "/opt/ros/groovy/lib/python2.7/dist-packages/tf/__init__.py", line 28, in <module>
    from _tf import *
ImportError: /opt/ros/groovy/lib/libroscpp.so: undefined symbol: _ZN6XmlRpc12XmlRpcSocket11s_use_ipv6_E
```

**Comment by sksellio** [comment]
Whatever Dirk did made it work. Yay!

**Comment by dirk-thomas** [comment]
Thanks for the laurels but I suppose it was just an inconsistent combination - parts of the installed packages already contained the IPv6 patch some did not.
If it reappears please reopen (or comment and someone will reopen).
