### ISSUE TITLE
roslaunch is missing a run dependency on rospkg

### ISSUE THREAD

**Issue by wjwwood** [ros/ros_comm#347]
When setting up tests for `xacro`, I installed only `ros-hydro-roslaunch` and `ros-hydro-rostest` and I get this traceback:

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/ros/xacro/src/xacro/__init__.py", line 44, in <module>
    from roslaunch import substitution_args
  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/__init__.py", line 46, in <module>
    import rospkg
ImportError: No module named rospkg
```

So I think `roslaunch` should run depend on `rospkg`.

**Comment by dirk-thomas** [comment]
I do agree that since `roslaunch` uses `rospkg` directly that it should also declare that run dependency itself.

But it already run depends on various other packages which run depend on rospkg so it looks like that you did not install all recursive run dependencies correctly in order to have the described problem in the first place.

**Comment by wjwwood** [comment]
Yeah, it is a problem where the debian packages installed for travis do not make it into the virtualenv for python. But I fixed it. Thanks.
