### ISSUE TITLE
roslaunch logger is not set up early enough

### ISSUE THREAD

**Issue by trainman419** [ros/ros_comm#490]
As seen on ROS Answers: http://answers.ros.org/question/190389/local-variable-logger-referenced-before-assignment/

If the package or launch file the user specified isn't found, an exception is thrown, but the logger used to log the exception is not set up.

```
ros@host1:~$ roslaunch openni2_launch openni2.launch
[openni2.launch] is neither a launch file in package [openni2_launch] nor is [openni2_launch] a launch file name
The traceback for the exception was written to the log file
Traceback (most recent call last):openni2_launch
  File "/opt/ros/indigo/bin/roslaunch", line 35, in <module>
    roslaunch.main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/__init__.py", line 292, in main
    logger.error(traceback.format_exc())
UnboundLocalError: local variable 'logger' referenced before assignment
```

**Comment by dirk-thomas** [comment]
Regression of #457.
