### ISSUE TITLE
[roslaunch-check] check_roslaunch() fails due to misnamed arg

### ISSUE THREAD

**Issue by jliviero** [ros/ros_comm#893]
```
jliviero:~/ws/src/ros_comm$ rosrun roslaunch roslaunch-check -t ../launch/
checking *.launch in directory ../launch/
checking ../launch/demospace.launch
Traceback (most recent call last):
  File "/home/jliviero/ws/src/ros_comm/tools/roslaunch/scripts/roslaunch-check", line 93, in <module>
    error_msg = check_roslaunch_dir(roslaunch_path, use_test_depends=options.test_depends)
  File "/home/jliviero/ws/src/ros_comm/tools/roslaunch/scripts/roslaunch-check", line 57, in check_roslaunch_dir
    error_msgs.append(check_roslaunch_file(roslaunch_file, use_test_depends=use_test_depends))
  File "/home/jliviero/ws/src/ros_comm/tools/roslaunch/scripts/roslaunch-check", line 46, in check_roslaunch_file
    error_msg = roslaunch.rlutil.check_roslaunch(roslaunch_file, use_test_depends=use_test_depends)
TypeError: check_roslaunch() got an unexpected keyword argument 'use_test_depends'
```

Incorrect name is provided for named arg; method defines the arg as `option_use_test_depends`, not `use_test_depends`.

See PR #892 for a fix.

**Comment by dirk-thomas** [comment]
Thank you for reporting this.
